# https://kubernetes.io/docs/concepts/services-networking/ingress/
# https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0
apiVersion: v1
kind: Service
metadata:  
  name: node-service
spec:
  selector:    
    app: node_kubernetes
  ports:  
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
