apiVersion: apps/v1

kind: Deployment

metadata:
  name: fe-deployment

  labels:
    app: react_kubernetes

spec:
  replicas: 1

  selector:
    matchLabels:
      app: react_kubernetes

  template:
    metadata:
      labels:
        app: react_kubernetes

    spec:
      containers:
        - name: react-kubernetes
          image: tejayerraguntla9/react_kubernetes
          ports:
            - containerPort: 3000
          env:
            - name: MODE
              value: production
            - name: NODE_APP_PROD
              value: http://node-service:8080

