# https://kubernetes.io/docs/concepts/services-networking/ingress/
# https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0
apiVersion: v1
kind: Service
metadata:  
  name: react-service
spec:
  selector:    
    app: react_kubernetes
  type: LoadBalancer
  ports:  
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30036
      protocol: TCP
